{
 "title": "InfraWatch",
 "tags": [ "infrawatch" ],
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Request Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "rps", "label": "Requests/s" }
   ],
   "targets": [
    {
     "expr": "rate(http_requests_total[$__rate_interval])",
     "legendFormat": "{{handler}} {{method}} {{status}}"
    }
   ]
  },
  {
   "title": "P95 Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "s", "label": "Latency" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[$__rate_interval])) by (le, handler, method))",
     "legendFormat": "{{handler}} {{method}}"
    }
   ]
  },
  {
   "title": "API Requests (Custom Counter)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Total requests" }
   ],
   "targets": [
    { "expr": "api_requests_total", "legendFormat": "API visits" }
   ]
  },
  {
   "title": "Container CPU Usage (cAdvisor)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percentunit", "label": "CPU" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{name!=\"\"}[5m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Container Memory Usage (cAdvisor)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "decmbytes", "label": "Memory (MB)" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{name!=\"\"} / 1024 / 1024",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Container Logs (Loki)",
   "type": "logs",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "targets": [
    {
     "expr": "{container=~\".+\"}"
    }
   ]
  }
 ]
}